# Generated by Django 3.1.3 on 2020-11-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoilTempModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam', models.CharField(choices=[('09:00', '09:00'), ('00:00', '00:00'), ('03:00', '03:00'), ('12:00', '12:00'), ('06:00', '06:00')], default='00:00', max_length=10)),
                ('suhu', models.FloatField()),
                ('kelembaban', models.FloatField()),
                ('tekanan', models.FloatField()),
                ('radiasi_matahari', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('rain_fall', models.FloatField()),
                ('cm_5', models.FloatField()),
                ('cm_10', models.FloatField()),
                ('cm_20', models.FloatField()),
                ('cm_50', models.FloatField()),
                ('cm_100', models.FloatField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
