# Generated by Django 3.1.3 on 2021-05-13 11:19

from django.db import migrations, models
import inputForm.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inputForm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilTempModelCilacap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam', models.CharField(choices=[('12:00', '12:00'), ('09:00', '09:00'), ('03:00', '03:00'), ('00:00', '00:00'), ('06:00', '06:00')], default='00:00', max_length=10)),
                ('suhu', models.FloatField(validators=[inputForm.validators.validate_temp])),
                ('kelembaban', models.FloatField(validators=[inputForm.validators.validate_humidity])),
                ('tekanan', models.FloatField(validators=[inputForm.validators.validate_press])),
                ('radiasi_matahari', models.FloatField(validators=[inputForm.validators.validate_SR])),
                ('wind_speed', models.FloatField(validators=[inputForm.validators.validate_WS])),
                ('rain_fall', models.FloatField(validators=[inputForm.validators.validate_rainfall])),
                ('cm_0', models.FloatField()),
                ('cm_2', models.FloatField()),
                ('cm_10', models.FloatField()),
                ('cm_20', models.FloatField()),
                ('cm_50', models.FloatField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='soiltempmodel',
            name='jam',
            field=models.CharField(choices=[('12:00', '12:00'), ('09:00', '09:00'), ('03:00', '03:00'), ('00:00', '00:00'), ('06:00', '06:00')], default='00:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='soiltempmodel',
            name='kelembaban',
            field=models.FloatField(validators=[inputForm.validators.validate_humidity]),
        ),
        migrations.AlterField(
            model_name='soiltempmodel',
            name='radiasi_matahari',
            field=models.FloatField(validators=[inputForm.validators.validate_SR]),
        ),
        migrations.AlterField(
            model_name='soiltempmodel',
            name='rain_fall',
            field=models.FloatField(validators=[inputForm.validators.validate_rainfall]),
        ),
        migrations.AlterField(
            model_name='soiltempmodel',
            name='suhu',
            field=models.FloatField(validators=[inputForm.validators.validate_temp]),
        ),
        migrations.AlterField(
            model_name='soiltempmodel',
            name='tekanan',
            field=models.FloatField(validators=[inputForm.validators.validate_press]),
        ),
        migrations.AlterField(
            model_name='soiltempmodel',
            name='wind_speed',
            field=models.FloatField(validators=[inputForm.validators.validate_WS]),
        ),
    ]
