# Generated by Django 3.1.3 on 2021-07-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputForm', '0010_auto_20210705_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soiltempmodelcilacap',
            old_name='radiasi_matahari',
            new_name='solar_radiation',
        ),
        migrations.AlterField(
            model_name='soiltempmodel',
            name='jam',
            field=models.CharField(choices=[('00:00', '00:00'), ('09:00', '09:00'), ('03:00', '03:00'), ('06:00', '06:00'), ('12:00', '12:00')], default='00:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='soiltempmodelcilacap',
            name='jam',
            field=models.CharField(choices=[('00:00', '00:00'), ('09:00', '09:00'), ('03:00', '03:00'), ('06:00', '06:00'), ('12:00', '12:00')], default='00:00', max_length=10),
        ),
    ]
