# Generated by Django 3.1.3 on 2021-07-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputForm', '0011_auto_20210713_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soiltempmodelcilacap',
            old_name='solar_radiation',
            new_name='radiasi_matahari',
        ),
        migrations.AlterField(
            model_name='soiltempmodel',
            name='jam',
            field=models.CharField(choices=[('09:00', '09:00'), ('06:00', '06:00'), ('03:00', '03:00'), ('00:00', '00:00'), ('12:00', '12:00')], default='00:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='soiltempmodelcilacap',
            name='jam',
            field=models.CharField(choices=[('09:00', '09:00'), ('06:00', '06:00'), ('03:00', '03:00'), ('00:00', '00:00'), ('12:00', '12:00')], default='00:00', max_length=10),
        ),
    ]
